defmodule Fiostats.Repo.Migrations.AddAccountsResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      modify :full_text_vector, :vector
    end

    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_number, :text, null: false
      add :name, :text, null: false
      add :classification, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:accounts, [:account_number],
             name: "accounts_unique_account_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:accounts, [:account_number],
                     name: "accounts_unique_account_number_index"
                   )

    drop table(:accounts)

    alter table(:transactions) do
      modify :full_text_vector, :vector
    end
  end
end
