defmodule Fiostats.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      add :validation_source, :text
    end
  end

  def down do
    alter table(:transactions) do
      remove :validation_source
    end
  end
end
