defmodule Fiostats.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      add :classification_reason, :text
    end
  end

  def down do
    alter table(:transactions) do
      remove :classification_reason
    end
  end
end
