defmodule Fiostats.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      add :classification_based_on_id,
          references(:transactions,
            column: :id,
            name: "transactions_classification_based_on_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:transactions, "transactions_classification_based_on_id_fkey")

    alter table(:transactions) do
      remove :classification_based_on_id
    end
  end
end
