defmodule Fiostats.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :external_id, :bigint, null: false
      add :date, :date, null: false
      add :title, :text, null: false
      add :amount, :decimal, null: false
      add :original_json, :map
      add :classification, :text
      add :full_text_vector, :vector, size: 1024
    end
  end

  def down do
    drop table(:transactions)
  end
end
