defmodule Fiostats.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      add :account, :text
    end
  end

  def down do
    alter table(:transactions) do
      remove :account
    end
  end
end
