defmodule :"Elixir.Fiostats.Repo.Migrations.Change to ci string" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      modify :title, :citext
    end
  end

  def down do
    alter table(:transactions) do
      modify :title, :text
    end
  end
end
