defmodule Fiostats.Repo.Migrations.AddShareToTransactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      add :share, :decimal, null: false, default: "1"
    end
  end

  def down do
    alter table(:transactions) do
      remove :share
    end
  end
end
